### ISSUE TITLE
Integrate in qelectrotech ?

### ISSUE THREAD

**Issue by tito125** [plc-user/QET_ElementScaler#1]
Is it possible to integrate it into qelectrotech? 

Is it possible to make a tuto with some examples.

**Comment by plc-user** [comment]
The question about integration in QET should go to the developers of QET. 
In my opinion the QUT-Element-Editor should provide the possibility to scale or even transform an element. But I know that the amount of developers in QET is very limited. That's why I created this QET_ElementScaler in a programming-language I know and where I found an example on how to handle XML-files.

Regarding a tutorial:
What question do you have?
What is not clear about the usage?
I thought that with the Batch- and Bash-Scripts that are available here many questions are answered...

**Comment by plc-user** [comment]
> Is it possible to integrate it into qelectrotech?
> 
> Is it possible to make a tuto with some examples.

The question about integration in QET should go to the developers of QET.
In my opinion the QUT-Element-Editor should provide the possibility to scale or even transform an element. But I know that the amount of developers in QET is very limited. That's why I created this QET_ElementScaler in a programming-language I know and where I found an example on how to handle XML-files.

Regarding a tutorial:
What question do you have?
What is not clear about the usage?
I thought that with the Batch- and Bash-Scripts that are available here many questions are answered...

**Comment by plc-user** [comment]
Re-open the issue when you want to answer the questions, tito125.

**Comment by tito125** [comment]
Hello,

With OS windows : batch cmd

and

Is this the default file folder to process?
DataPfad=Z:\win\Elemente
I don't understand 

Can you show me step by step how to use it, thank you

**Comment by plc-user** [comment]
Hi tito125!

Still I don't know what your problem is. Don't expect general information on how to use the command-line!
QET_ElementScaler does NOT support graphical use with a mouse or so!

Do you only want to use the software? 
Then you have to download the suitable release-version for your OS and run it like this:
&lt;Path_to_executable&gt;QET_ElementScaler.exe &lt;Path_to_ElementFile&gt;FileName.elmt &lt;Scaling-Factor&gt;

Example for Win:
C:\Tools\QET_ElementScaler.exe c:\data\QET-Elements\controller.elmt 0.75

This results in a file named "controller_SCALED.elmt" in the same directory where the original file is.

**Comment by tito125** [comment]
hello,
Thanks for the feedback,

I have understood and I have modified the batch file, with a little bit of user-friendliness to test if it helps others.

I could have gone even further by asking for the language of the program with 1 English 2 German 3 French, but I find it good for me.
To download 
https://www.grosfichiers.com/CuFhFMuUTjv_epqwr33T6gq

**Comment by plc-user** [comment]
### Information:
Current devel-version of QElectroTech has build-in support for QET_ElementScaler:
In Element-editor there is a sub-menu "File"->"Import scaled element" where the binary of QET_ElementScaler is called from within the GUI to import scaled elements directly to graphical element-editor.
